services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"  
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  
      MONGO_INITDB_ROOT_PASSWORD: example  
      MONGO_INITDB_DATABASE: geo-map
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:  